name: Quality Checks

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Quality Checks
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        sp_naive: ["", "sp-naive"]
        non_zero_vma: ["", "non-zero-vma"]
        arm_el2: ["", "arm-el2"]
        preempt: ["", "preempt"]
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-none
          - riscv64gc-unknown-none-elf
          - aarch64-unknown-none-softfloat
          - loongarch64-unknown-none-softfloat
          - armv7a-none-eabi

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src, clippy, rustfmt
          targets: ${{ matrix.target }}

      - name: Check rust version
        run: rustc --version --verbose

      - name: Check code format
        run: cargo fmt --all -- --check

      - name: "Build (sp: ${{ matrix.sp_naive }}, nz-vma: ${{ matrix.non_zero_vma }}, el2: ${{ matrix.arm_el2 }}, preempt: ${{ matrix.preempt }})"
        run: cargo build --target ${{ matrix.target }} --features "${{ matrix.sp_naive }},${{ matrix.non_zero_vma }},${{ matrix.arm_el2 }},${{ matrix.preempt }}"

      - name: "Clippy (sp: ${{ matrix.sp_naive }}, nz-vma: ${{ matrix.non_zero_vma }}, el2: ${{ matrix.arm_el2 }}, preempt: ${{ matrix.preempt }})"
        run: cargo clippy --target ${{ matrix.target }} --features "${{ matrix.sp_naive }},${{ matrix.non_zero_vma }},${{ matrix.arm_el2 }},${{ matrix.preempt }}"
