name: Test

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        feature_set:
          - "sp-naive"
          - "sp-naive,non-zero-vma"
          - "sp-naive,preempt"
          - "sp-naive,non-zero-vma,preempt"
          - "non-zero-vma"
          - "non-zero-vma,preempt"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Run tests (${{ matrix.feature_set }})
        run: cargo test --target x86_64-unknown-linux-gnu --features "${{ matrix.feature_set }}" -- --nocapture --test-threads=1
